[global]
type=global
endpoint_identifier_order=username,ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[zoiper]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=alaw
auth=zoiper-auth
aors=zoiper

[zoiper-auth]
type=auth
auth_type=userpass
username=zoiper
password=secret

[zoiper]
type=aor
max_contacts=2
remove_existing=yes

[twilio-trunk]
type=endpoint
context=inbound-calls
disallow=all
allow=ulaw
allow=alaw
direct_media=no

[twilio-trunk-identify]
type=identify
endpoint=twilio-trunk
match=54.172.60.0/23
match=54.244.51.0/24
match=54.171.127.192/26
match=35.156.191.128/25